### ISSUE TITLE
Feature: visualize novel alternative splice variants 

### ISSUE THREAD

**Issue by husamia** [UK-SBCoA-EbbertLab/RNApysoforms#3]
I am interested in studying how predictions of splice variants. For example, splice variants leads to cryptic splice site and alternative splice variants. Can you suggest how to visualize those splice variants?

**Comment by bernardo-heberle** [comment]
Hi @husamia, thanks for your interest in our work.

If you have an annotation that includes the start and end sites for cryptic exons in your splice variants, you should be able to achieve this.

We provide several examples that might be adaptable to your needs:

[Custom Color Maps](https://rna-pysoforms.readthedocs.io/en/latest/examples/07.custom_color_maps.html)
[Separate CDS Interactivity](https://rna-pysoforms.readthedocs.io/en/latest/examples/08.separate_CDS_interactivity.html)

With an annotation that identifies the cryptic exons, you can create a column to distinguish cryptic from non-cryptic exons. This way, you can display them in different colors on the plot, as shown in the examples above.

If you are having trouble doing this, but have some example data and can provide a sketch of the plot you are envisioning I can try to help you further. 

Hope this helps!

**Comment by bernardo-heberle** [comment]
Hi @husamia, I am closing this issue. Feel free to re-open it if you need help or have questions.
